"use strict";

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("Owners", [
      {
        id: 1,
        firstName: "Daryl",
        lastName: "McGreal",
        phoneNumber: 8656243559,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2,
        firstName: "Jefferson",
        lastName: "Rihosek",
        phoneNumber: 8209180722,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 3,
        firstName: "Lira",
        lastName: "Madner",
        phoneNumber: 9445014421,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 4,
        firstName: "Erl",
        lastName: "Darker",
        phoneNumber: 9413262737,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 5,
        firstName: "Archie",
        lastName: "Tidey",
        phoneNumber: 9519534019,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 6,
        firstName: "Magnum",
        lastName: "Pilley",
        phoneNumber: 5675500579,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 7,
        firstName: "Kimberlee",
        lastName: "Hanbridge",
        phoneNumber: 9053438898,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 8,
        firstName: "Kirbee",
        lastName: "Booler",
        phoneNumber: 6268626803,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 9,
        firstName: "Sally",
        lastName: "McAughtrie",
        phoneNumber: 3884220915,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 10,
        firstName: "Link",
        lastName: "Kiffe",
        phoneNumber: 2047644504,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 11,
        firstName: "Aviva",
        lastName: "Gudd",
        phoneNumber: 2946443590,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 12,
        firstName: "Lani",
        lastName: "Lisett",
        phoneNumber: 7414507932,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 13,
        firstName: "Willard",
        lastName: "Pestricke",
        phoneNumber: 3693027795,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 14,
        firstName: "Dietrich",
        lastName: "Rymill",
        phoneNumber: 1256617104,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 15,
        firstName: "Janos",
        lastName: "Olek",
        phoneNumber: 2286087850,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("Owners", null, {});
  },
};
