"use strict";

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("Pets", [
      {
        id: 1,
        name: "Isidore",
        age: 77,
        weight: 88,
        gender: "Male",
        breed: "Indian porcupine",
        storeID: "1",
        ownerID: "11",
        hasShots: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2,
        name: "Jenni",
        age: 5,
        weight: 5,
        gender: "Female",
        breed: "Cat, kaffir",
        storeID: "3",
        ownerID: "10",
        hasShots: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 3,
        name: "Nevsa",
        age: 74,
        weight: 16,
        gender: "Female",
        breed: "Ring-tailed gecko",
        storeID: "1",
        ownerID: "2",
        hasShots: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 4,
        name: "Kerry",
        age: 31,
        weight: 90,
        gender: "Female",
        breed: "Frilled lizard",
        storeID: "3",
        ownerID: "14",
        hasShots: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 5,
        name: "Marylee",
        age: 68,
        weight: 41,
        gender: "Female",
        breed: "Common nighthawk",
        storeID: "1",
        ownerID: "10",
        hasShots: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 6,
        name: "Alvan",
        age: 55,
        weight: 59,
        gender: "Male",
        breed: "Flightless cormorant",
        storeID: "3",
        ownerID: "8",
        hasShots: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 7,
        name: "Donnamarie",
        age: 67,
        weight: 71,
        gender: "Female",
        breed: "Cottonmouth",
        storeID: "3",
        ownerID: "6",
        hasShots: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 8,
        name: "Rodolphe",
        age: 52,
        weight: 91,
        gender: "Male",
        breed: "Kite, black",
        storeID: "2",
        ownerID: "2",
        hasShots: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 9,
        name: "Sutton",
        age: 52,
        weight: 74,
        gender: "Male",
        breed: "White stork",
        storeID: "2",
        ownerID: "8",
        hasShots: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 10,
        name: "Randell",
        age: 86,
        weight: 73,
        gender: "Male",
        breed: "Boa, columbian rainbow",
        storeID: "1",
        ownerID: "4",
        hasShots: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 11,
        name: "Barnie",
        age: 14,
        weight: 38,
        gender: "Male",
        breed: "Trumpeter, dark-winged",
        storeID: "2",
        ownerID: "3",
        hasShots: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 12,
        name: "Aurel",
        age: 45,
        weight: 6,
        gender: "Female",
        breed: "Spotted-tailed quoll",
        storeID: "2",
        ownerID: "14",
        hasShots: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 13,
        name: "Greer",
        age: 39,
        weight: 60,
        gender: "Female",
        breed: "Ring dove",
        storeID: "2",
        ownerID: "8",
        hasShots: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 14,
        name: "Barbabas",
        age: 53,
        weight: 86,
        gender: "Male",
        breed: "Southern ground hornbill",
        storeID: "3",
        ownerID: "6",
        hasShots: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 15,
        name: "Hashim",
        age: 90,
        weight: 47,
        gender: "Male",
        breed: "Tsessebe",
        storeID: "3",
        ownerID: "7",
        hasShots: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 16,
        name: "Korry",
        age: 36,
        weight: 88,
        gender: "Female",
        breed: "Zorilla",
        storeID: "1",
        ownerID: "9",
        hasShots: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 17,
        name: "Garvy",
        age: 10,
        weight: 99,
        gender: "Male",
        breed: "Otter, brazilian",
        storeID: "1",
        ownerID: "7",
        hasShots: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 18,
        name: "Nettle",
        age: 62,
        weight: 47,
        gender: "Female",
        breed: "Screamer, southern",
        storeID: "2",
        ownerID: "10",
        hasShots: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 19,
        name: "Shepherd",
        age: 35,
        weight: 93,
        gender: "Male",
        breed: "Southern brown bandicoot",
        storeID: "2",
        ownerID: "6",
        hasShots: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 20,
        name: "Pauline",
        age: 5,
        weight: 50,
        gender: "Female",
        breed: "Western grey kangaroo",
        storeID: "2",
        ownerID: "14",
        hasShots: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("Pets", null, {});
  },
};
